"""
01_basics_and_parsers.py
========================
Module: Core Concepts - LangChain Basics, Models, Prompts, and Output Parsers

This module introduces the fundamental building blocks of LangChain:
1. Initializing Chat Models (Google Gemini & OpenAI via init_chat_model).
2. Constructing Prompts (ChatPromptTemplate, FewShotChatMessagePromptTemplate).
3. LangChain Expression Language (LCEL) syntax: `prompt | model | parser`.
4. Execution Modes: Single Invocation (`invoke`), Batching (`batch`), and Streaming (`stream`).
5. Schema Inspection: Examining input and output JSON schemas of runnables.
6. Structured Output and Parsers:
   - StrOutputParser (raw string)
   - JsonOutputParser (JSON dictionary)
   - PydanticOutputParser (strongly typed objects with validation)
   - `.with_structured_output()` (native model-level schema enforcement)

Prerequisites:
- Set GOOGLE_API_KEY or OPENAI_API_KEY in your `.env` file.
"""

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, FewShotChatMessagePromptTemplate
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser, PydanticOutputParser
from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from pydantic import BaseModel, Field

# Load environment variables (.env file containing API keys)
load_dotenv()


# ============================================================================
# 1. BASIC LCEL CHAIN & EXECUTION MODES
# ============================================================================

def demo_basic_chain():
    """
    Demonstrates the simplest LCEL (LangChain Expression Language) chain:
        Prompt -> Model -> Output Parser
    
    The pipe operator `|` connects components:
    - `prompt`: Transforms an input dictionary into a list of messages.
    - `model`: Sends the messages to Gemini and returns an AIMessage.
    - `parser`: Extracts the clean string content from the AIMessage.
    """
    print("\n--- 1. Basic LCEL Chain (Batch Invocation) ---")

    # 1. Define Prompt Template with a {question} placeholder
    prompt = ChatPromptTemplate.from_template(
        "You are a helpful assistant. Answer in one sentence: {question}"
    )

    # 2. Instantiate the Chat Model (Gemini 2.5 Flash)
    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)

    # 3. Parse output as plain string
    parser = StrOutputParser()

    # 4. Compose the chain using the pipe operator |
    chain = prompt | model | parser

    # Batch execution: Process multiple inputs concurrently in a single call
    inputs = [
        {"question": "Who is the prime minister of India?"},
        {"question": "Who won Game of the Year in 2020?"}
    ]

    print("Running batch inputs...")
    results = chain.batch(inputs)

    for item, result in zip(inputs, results):
        print(f"  Input: {item['question']}")
        print(f"  Output: {result}\n")


def demo_streaming():
    """
    Demonstrates real-time token streaming.
    Instead of waiting for the full response, `chain.stream()` yields chunks
    as they are generated by the model. Ideal for interactive UIs.
    """
    print("\n--- 2. Streaming Output Demonstration ---")

    prompt = ChatPromptTemplate.from_template("Write a haiku about {topic}")
    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)
    parser = StrOutputParser()

    chain = prompt | model | parser

    print("Streaming haiku about 'nature':\n")
    # chain.stream() yields tokens incrementally
    for chunk in chain.stream({"topic": "nature"}):
        print(chunk, end="", flush=True)
    print("\n")


def demo_schema_inspection():
    """
    Demonstrates how LCEL runnables expose their expected input and output schemas.
    This helps with debugging, automated UI generation, and validating pipelines.
    """
    print("\n--- 3. Schema Inspection ---")

    prompt = ChatPromptTemplate.from_template("Write a haiku about {topic}")
    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)
    parser = StrOutputParser()

    chain = prompt | model | parser

    # Inspect the expected input schema (expects a dictionary with key 'topic')
    input_schema = chain.input_schema.model_json_schema()
    # Inspect the generated output schema (produces a string)
    output_schema = chain.output_schema.model_json_schema()

    print(f"Expected Input Schema: {input_schema}")
    print(f"Generated Output Schema: {output_schema}")


def product_chain():
    """
    Example of a single-input chain producing a marketing tagline.
    """
    print("\n--- 4. Product Tagline Chain ---")

    prompt = ChatPromptTemplate.from_template(
        "Write a catchy product tagline for this product: {product}"
    )
    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)
    parser = StrOutputParser()

    product_name = "Game Boy"
    chain = prompt | model | parser

    result = chain.invoke({"product": product_name})
    print(f"Product: {product_name} => Tagline: {result}")


# ============================================================================
# 2. CHAT MODEL INITIALIZATION & MULTI-TURN MESSAGES
# ============================================================================

def demo_chat_model():
    """
    Demonstrates modern model initialization using `init_chat_model`.
    `init_chat_model` provides a provider-agnostic way to load models
    (OpenAI, Google GenAI, Anthropic, Ollama, etc.) with unified parameters.
    """
    print("\n--- 5. Provider-Agnostic init_chat_model ---")

    chat_model = init_chat_model(
        model="gemini-2.5-flash",
        model_provider="google_genai",
        temperature=0.7,
        streaming=True,
        max_retries=3,
    )

    response = chat_model.invoke("What is the capital of France?")
    print(f"Response: {response.content}")
    return chat_model


def demo_message():
    """
    Demonstrates low-level message interaction using explicit message objects:
    - SystemMessage: Sets model persona, guidelines, or tone.
    - HumanMessage: User queries.
    - AIMessage: Assistant responses.
    
    Shows how conversation state is manually preserved by appending past turns.
    """
    print("\n--- 6. Multi-Turn Conversation with Explicit Messages ---")

    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)

    # Initial context + question
    messages = [
        SystemMessage(content="Answer every question in an Aussie accent."),
        HumanMessage(content="How was the match yesterday?")
    ]

    response = model.invoke(messages)
    print(f"Turn 1 Response: {response.content}")

    # Append assistant's answer and user's follow-up to maintain context
    messages.append(response)
    messages.append(HumanMessage(content="What did I ask you before?"))

    response = model.invoke(messages)
    print(f"Turn 2 Response: {response.content}")


def exercise_multi_model():
    """
    Demonstrates comparing responses across multiple models or versions
    using a standardized loop and `init_chat_model`.
    """
    print("\n--- 7. Comparing Multiple Models ---")

    models = ["gemini-2.5-flash"]

    for model_name in models:
        chat_model = init_chat_model(
            model=model_name,
            model_provider="google_genai",
            temperature=0.7,
            streaming=True,
            max_retries=3,
        )

        response = chat_model.invoke("Write a sentence about pyramids.")
        print(f"[{model_name}]: {response.content}")


# ============================================================================
# 3. ADVANCED PROMPT TEMPLATES (MULTI-MESSAGE & FEW-SHOT)
# ============================================================================

def prompt_messages():
    """
    Demonstrates formatting a ChatPromptTemplate with dynamic placeholders.
    """
    print("\n--- 8. Basic ChatPromptTemplate Formatting ---")

    prompt = ChatPromptTemplate.from_template("Recommend me a game of {genre} about {topic}")
    messages = prompt.format_messages(genre="Adventure", topic="Monsters")
    print(f"Formatted Messages: {messages}")


def multi_prompt():
    """
    Demonstrates structured multi-role prompts with (role, template) tuples.
    Allows injecting dynamic parameters into system prompts as well as user messages.
    """
    print("\n--- 9. Multi-Role Prompt Template ---")

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are a translator that translates {input} to {output}."),
            ("human", "Translate this text: {text}")
        ]
    )

    formatted_messages = prompt.format_messages(
        input="English",
        output="Tamil",
        text="I am going to the market"
    )

    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)
    response = model.invoke(formatted_messages)

    print(f"Input: 'I am going to the market' -> Translated: {response.content}")


def few_shot():
    """
    Demonstrates Few-Shot Prompting using FewShotChatMessagePromptTemplate.
    Few-shot prompting provides in-context examples to guide the model's
    style, tone, or format without fine-tuning.
    """
    print("\n--- 10. Few-Shot Chat Prompt Template ---")

    # 1. Define example input-output pairs
    examples = [
        {"input": "happy", "output": "sad"},
        {"input": "big", "output": "small"},
    ]

    # 2. Template for how each example should be formatted
    example_prompt = ChatPromptTemplate.from_messages(
        [
            ("human", "{input}"),
            ("ai", "{output}")
        ]
    )

    # 3. Assemble the few-shot container
    few_shot_prompt = FewShotChatMessagePromptTemplate(
        example_prompt=example_prompt,
        examples=examples
    )

    # 4. Combine with the target query
    final_prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are an antonym generator. Output only the antonym word."),
            few_shot_prompt,
            ("human", "{input}")
        ]
    )

    model = init_chat_model(model="gemini-2.5-flash", model_provider="google_genai", temperature=0.7)
    chain = final_prompt | model | StrOutputParser()

    result = chain.invoke({"input": "tall"})
    print(f"Antonym for 'tall': {result}")


# ============================================================================
# 4. STRUCTURED OUTPUT & OUTPUT PARSERS
# ============================================================================

def output_parsers():
    """
    Demonstrates extracting strictly typed data using:
    1. PydanticOutputParser: Uses prompt instructions + schema parsing.
    2. Model-native Structured Output (`with_structured_output`):
       Leverages model function-calling / JSON schema constraints directly.
    """
    print("\n--- 11. Structured Output and Pydantic Parsers ---")

    # Define Pydantic models for expected schemas
    class Person(BaseModel):
        name: str = Field(description="Name of the person")
        age: int = Field(description="Age of the person")
        occupation: str = Field(description="Job or profession of the person")

    class MovieReview(BaseModel):
        title: str = Field(description="Name of the movie")
        review: str = Field(description="Review summary of the movie")
        rating: float = Field(description="Rating of the movie out of 10")

    # Approach A: PydanticOutputParser (works across any LLM via format instructions)
    parser = PydanticOutputParser(pydantic_object=Person)

    prompt = ChatPromptTemplate.from_template(
        "Extract details from this bio:\n{description}\n\n{format_instructions}"
    ).partial(format_instructions=parser.get_format_instructions())

    model = init_chat_model(model="gemini-2.5-flash", model_provider="google_genai", temperature=0)

    chain = prompt | model | parser
    person_result = chain.invoke(
        {"description": "Marie is a 22 year old who is working as a Marketing intern at Microsoft"}
    )
    print(f"Pydantic Parsed Object: {person_result}")
    print(f"  Name: {person_result.name}, Age: {person_result.age}, Job: {person_result.occupation}\n")

    # Approach B: Native with_structured_output (Recommended for modern models)
    structured_model = model.with_structured_output(MovieReview)
    review_result = structured_model.invoke(
        "Review: Odyssey is a great film by Nolan, would give a solid 9.5/10"
    )
    print(f"Native Structured Output Object: {review_result}")
    print(f"  Title: {review_result.title}, Rating: {review_result.rating}/10")


# ============================================================================
# MAIN ENTRYPOINT
# ============================================================================

def main():
    """
    Run the demos. Uncomment any specific function to run its example.
    """
    print("=" * 60)
    print("LANGCHAIN CORE CONCEPTS: BASICS, PROMPTS & OUTPUT PARSERS")
    print("=" * 60)

    demo_basic_chain()
    demo_streaming()
    demo_schema_inspection()
    product_chain()
    demo_chat_model()
    demo_message()
    few_shot()
    output_parsers()


if __name__ == "__main__":
    main()
